backend:
  name: github
  repo: thomascrenshaw/grumpy-pickleballer
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://grumpypickleballer.com"

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "blurb", label: "Blurb", widget: "string", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - {
          name: "coverImage",
          label: "Cover Image",
          widget: "image",
          required: false,
        }
      - { name: "body", label: "Body", widget: "markdown" }
